### ISSUE TITLE
Ices Version

### ISSUE THREAD

**Issue by mariomurrent-softwaresolutions** [mjamroz/ices-radio-scripts#1]
This does not work for ices2 right? For which Ices version is this?

**Comment by mjamroz** [comment]
@mariomurrent-softwaresolutions i would say so. Im not sure cause that code was developed 8 years ago. But I put ices config file there:
https://github.com/mjamroz/ices-radio-scripts/blob/master/ices.conf
if that is the same like ices then that is ices, not ices2

but in general those scripts are very simple. one just starts ices and restart (by crontab) ices, if necessary. and another script (changeSong) will change song if exec manually. nothing special at all.

**Comment by mariomurrent-softwaresolutions** [comment]
Does not work for ices2
